# Generated by Django 5.1.4 on 2025-02-24 09:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=22)),
                ('tos_accept', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=1)),
                ('level_name', models.CharField(default='Newbie', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workout.chathistory')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('body_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('protein_intake', models.DecimalField(decimal_places=1, max_digits=5)),
                ('judgment', models.CharField(choices=[('◎', '◎'), ('〇', '〇'), ('△', '△'), ('×', '×')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.user')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('conversation_type', models.CharField(default='recent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.user')),
            ],
        ),
        migrations.AddField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.user'),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.user')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=999)),
                ('repetitions', models.DecimalField(decimal_places=1, max_digits=999)),
                ('category', models.CharField(default='Strength Training', max_length=50)),
                ('target_muscle', models.CharField(choices=[('soubou', '僧帽筋'), ('chest', '胸筋'), ('kouhaikin', '広背筋'), ('trapsmiddle', '背中中部'), ('shoulders', '肩'), ('biceps', '上腕二頭筋'), ('triceps', '上腕三頭筋'), ('zenwan', '前腕'), ('abs', '腹筋'), ('hukushakin', '腹斜筋'), ('quads', '大腿四頭筋'), ('hamstrings', 'ハムストリングス'), ('calves', 'ふくらはぎ'), ('lowerback', '腰部'), ('glutes', '臀筋')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle', models.CharField(choices=[('soubou', '僧帽筋'), ('chest', '胸筋'), ('kouhaikin', '広背筋'), ('trapsmiddle', '背中中部'), ('shoulders', '肩'), ('biceps', '上腕二頭筋'), ('triceps', '上腕三頭筋'), ('zenwan', '前腕'), ('abs', '腹筋'), ('hukushakin', '腹斜筋'), ('quads', '大腿四頭筋'), ('hamstrings', 'ハムストリングス'), ('calves', 'ふくらはぎ'), ('lowerback', '腰部'), ('glutes', '臀筋')], max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.user')),
            ],
            options={
                'unique_together': {('user', 'muscle')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyMuscleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle', models.CharField(choices=[('soubou', '僧帽筋'), ('chest', '胸筋'), ('kouhaikin', '広背筋'), ('trapsmiddle', '背中中部'), ('shoulders', '肩'), ('biceps', '上腕二頭筋'), ('triceps', '上腕三頭筋'), ('zenwan', '前腕'), ('abs', '腹筋'), ('hukushakin', '腹斜筋'), ('quads', '大腿四頭筋'), ('hamstrings', 'ハムストリングス'), ('calves', 'ふくらはぎ'), ('lowerback', '腰部'), ('glutes', '臀筋')], max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('year_month', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.user')),
            ],
            options={
                'unique_together': {('user', 'muscle', 'year_month')},
            },
        ),
    ]
